name: RT model history

on:
  push:
    branches: [ "update_rt_model" ]
jobs:
  memote-history:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'

    - name: Install memote
      run: pip install memote cobra

    - name: Setup variables
      id: setup
      run: |
        echo "history=rt_history_report.html" >> $GITHUB_ENV
        echo "deployment=gh-pages" >> $GITHUB_ENV
        echo "other-repo=gh-pages-repo" >> $GITHUB_ENV
        echo "MEMOTE_LOCATION=sqlite:///results.db" >> $GITHUB_ENV

    - name: Checkout repo for gh-pages branch
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: ${{ env.deployment }}
        path: ${{ env.other-repo }}

    - name: Memote short run
      run: |
        git config --global user.name "memote-bot"
        memote run models/rhodosporidium_toruloides_ifo_08804/Rhodo_Toru.xml 
        

    - name: Compute Memote history on push
      run: |
        # Generate the history report on the deployment branch
        memote report history \
        --model models/rhodosporidium_toruloides_ifo_08804/Rhodo_Toru.xml \
        --filename="${{ env.other-repo }}/${{ env.history }}"

    - name: Auto-commit results
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        commit_user_name: memote-bot
        commit_message: "chore: update memote history report"
        file_pattern: ${{ env.history }}
        branch: ${{ env.deployment }}
        repository: ${{ env.other-repo }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}