name: RT model history

on:
  push:
    branches: [ "update_rt_model" ]
jobs:
  memote-history:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'

    - name: Install memote
      run: pip install memote cobra

    - name: Setup variables
      id: setup
      run: |
        echo "MEMOTE_LOCATION=sqlite:///results.db" >> $GITHUB_ENV

    - name: Memote short run
      run: |
        git config --global user.name "memote-bot"
        git checkout gh-pages
        git checkout update_rt_model
        memote run models/rhodosporidium_toruloides_ifo_08804/Rhodo_Toru.xml \
        --location  ${{ env.MEMOTE_LOCATION }} \
        --experimental=models/rhodosporidium_toruloides_ifo_08804/data/experiments.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compute Memote history on push
      run: |
        # Generate the history report on the deployment branch
        git checkout gh-pages
        memote report history \
        --model models/rhodosporidium_toruloides_ifo_08804/Rhodo_Toru.xml \
        --filename="rt_history_report.html"

    - name: Auto-commit results
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        commit_user_name: memote-bot
        commit_message: "chore: update memote history report"
        file_pattern: rt_history_report.html
        branch: gh-pages
        repository: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}